---
permalink: phases/plan-prepare-phase.html 
sidebar: sidebar 
keywords: plan and prepare phase, foreign lun import, fli, migration planning, test migration, cutover, intercluster lif, iscsi fli, gap analysis, san migration, fc fli, zoning, test migration 
summary: Führen Sie eine oder mehrere Testmigrationen durch, um zu bestätigen, dass die Arrays, das Netzwerk und die Fabric, die ONTAP-Konfiguration und die Host-Behebungsschritte korrekt sind, und um Durchsatzproben zu sammeln, die für die Produktionsplanung hochgerechnet werden können. 
---
= ONTAP Foreign LUN Import (FLI) Testmigration und Umstellungsplanung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Führen Sie eine oder mehrere Testmigrationen durch, um zu bestätigen, dass die Arrays, das Netzwerk und die Fabric, die ONTAP-Konfiguration und die Host-Behebungsschritte korrekt sind, und um Durchsatzproben zu sammeln, die für die Produktionsplanung hochgerechnet werden können.

Eine gute Testmigration bestätigt:

* Backend-Bereitschaft: Die Erreichbarkeit des IC LIF, die Stabilität der iSCSI-Sitzungen und die Erkennung fremder LUNs sind über alle Pfade hinweg konsistent.
* Workflow-Korrektheit: Die Importbeziehungserstellung/-start/-anzeige/-abschluss (und optional die Überprüfung) verhält sich im gewählten Modus (online/offline) wie erwartet.
* Host-Bereitschaft: Die Schritte zum erneuten Scannen/Sanieren des Hosts funktionieren zuverlässig für den jeweiligen Anwendungsfall (z. B. ESXi VMFS/RDM, Windows Standalone/WFC).
* Operative Schätzungen: Der in Testläufen beobachtete Durchsatz bietet die realistischste Grundlage für die Schätzung der Produktionsmigrationsdauer und ist im Allgemeinen besser als jeder generische Benchmark.




== Testbeispiel für die Migration mit Hitachi AMS2100

Im Folgenden finden Sie ein Beispiel für eine Testmigration mit einem Hitachi AMS2100 als Fremdarray. Abhängig von den betroffenen Arrays, Host-Betriebssystemen und anderen Variablen können die Schritte unterschiedlich sein.

Nutzen Sie das folgende Beispiel als allgemeinen Leitfaden für die zur Durchführung von Testmigrationen erforderlichen Schritte. NetApp empfiehlt die Durchführung von Testmigrationen so früh wie möglich, um Probleme zu finden und so lange wie möglich zu beheben. Vor der Durchführung der Produktionmigration sollten alle Kombinationen aus Quell- und Ziel-Arrays in einem Test durchgeführt werden.

.Schritte
. Erstellen Sie eine 2 GB Test-LUN auf dem Quell-Array.
+
.. Melden Sie sich bei Hitachi Storage Navigator Modular als  `system` an.
.. Wählen Sie *AMS 2100 array*.
.. Klicken Sie auf *Array anzeigen und konfigurieren*.
.. Melden Sie sich mit  `root` an.
.. Erweitern Sie *Gruppen* und wählen Sie *logische Einheiten*.
.. Wählen Sie *LU erstellen*, um die Test-LUN zu erstellen.
.. Erstellen Sie eine Test-LUN mit 2 GB.
.. Klicken Sie auf *OK*.
.. Überspringen Sie die LUN-Zuweisung hier und fahren Sie mit *Schließen* fort.
.. Überprüfen Sie, ob die Test-LUN erstellt wurde.


. Weisen Sie die Test-LUN der für ONTAP-Initiatoren erstellten Hostgruppe zu.
+
.. Erweitern Sie *Gruppen* und wählen Sie *logische Einheiten*.
.. Wählen Sie *Host Groups* aus, um die Test-LUN der Hostgruppe *cDOT_FLI* zuzuordnen.
.. Wählen Sie die im vorherigen Schritt erstellte Hostgruppe *cDOT_FLI* aus und klicken Sie auf *Hostgruppe bearbeiten*.
.. Wählen Sie die Ports für die Hostgruppe aus. In diesem Beispiel wählen wir *0a*, *0e*, *1a*, *1e*. Wählen Sie die Option *Forced Set to All Selected Ports* aus.
.. Bearbeiten Sie im HDS Storage Navigator die Hostgruppe.
.. Klicken Sie auf *Logische Einheiten* und fügen Sie die Test-LUN hinzu.
.. Klicken Sie auf *OK*, um die LUN zuzuordnen.
.. Wählen Sie *Ja, ich habe die oben genannte Warnung gelesen und möchte Hostgruppe* bearbeiten und auf *Bestätigen* klicken.
.. Überprüfen Sie die Erstellung der Host-Gruppe, und klicken Sie auf *Schließen*.


. Überprüfen Sie die Test-LUN und -Zuordnung vom Quell-Storage zu Ziel-Storage und führen Sie den Import fremder LUNs (Foreign LUN Import, FLI) durch.
+
.. Melden Sie sich über SSH beim ONTAP-Speicher mit dem  `admin` Benutzer an.
.. Stellen Sie den Modus auf *Erweitert* ein.
+
DataMig-cmode::> set -privilege advanced

.. Geben Sie 'y' ein, wenn Sie gefragt werden, ob Sie mit erweiterten Befehlen fortfahren möchten.
.. Ermitteln Sie das Quell-Array auf ONTAP. Warten Sie einige Minuten und versuchen Sie dann erneut, das Quell-Array zu ermitteln.
+
Speicherarray anzeigen

+
Wenn das Storage-Array zum ersten Mal erkannt wird, wird das Array von ONTAP möglicherweise nicht durch die automatische Erkennung angezeigt. Verwenden Sie die folgenden Anweisungen, um den Switch-Port zurückzusetzen, an dem ONTAP-Initiator-Ports angeschlossen sind.

+
Beispielsweise sind die DataMig-cmode-Cluster-Initiator-Ports `0a` und `0b` von ONTAP mit Cisco-Ports `4/9` und `4/11` verbunden. Um Port `4/9` auf dem Cisco Switch zurückzusetzen:

+
[listing]
----
conf t
interface fc4/
shutdown
no shutdown
exit
exit
----
+
Das Zurücksetzen eines Ports reicht in der Regel aus. Überprüfen Sie nach dem Zurücksetzen eines Ports die Array-Liste und die LUN-Pfade.

.. Überprüfen Sie, ob das Quell-Array über alle Initiator-Ports erkannt wird:
+
storage array config show -array-name HITACHI_DF600F_1

+
[listing]
----
             LUN   LUN
Node         Group Count     Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- -----------------------
DataMig-cmode-01 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
DataMig-cmode-02 0     1    HITACHI_DF600F_1     50060e801046b960        0a
                                                 50060e801046b964        0b
                                                 50060e801046b968        0a
                                                 50060e801046b96c        0b
----
.. Listen Sie die vom Hitachi-Speicher zugeordneten Test-LUNs auf und überprüfen Sie die Festplatteneigenschaften und Pfade:
+
storage disk show -array-name HITACHI_DF600F_1 -instance

+
[listing]
----

                  Disk: HIT-1.1
        Container Type: unassigned
            Owner/Home: -  / -
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: HITACHI_DF600F_1
                Vendor: HITACHI
                 Model: DF600F
         Serial Number: 83017542001A
                   UID: 48495441:43484920:38333031:37353432:30303236:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: -
              Position: present
Checksum Compatibility: block
             Aggregate: -
                  Plex: -
Paths:
                                LUN  Initiator Side        Target Side                                            Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port     TPGN    Speed  I/O KB/s  IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  --------------  ------  ----   --- -----
DataMig-cmode-01   0a             0  DM-Cisco9506-1:4-9    DM-Cisco9506-1:2-24   AO  INU  50060e801046b968  2   2 Gb/S    0  0
DataMig-cmode-01   0b             0  DM-Cisco9506-2:4-9    DM-Cisco9506-2:2-24   AO  INU  50060e801046b96c  2   2 Gb/S    0  0
DataMig-cmode-01   0b             0  DM-Cisco9506-2:4-9    DM-Cisco9506-2:1-14   AO  INU  50060e801046b964  1   2 Gb/S    0  0
DataMig-cmode-01   0a             0  DM-Cisco9506-1:4-9    DM-Cisco9506-1:1-14   AO  INU  50060e801046b960  1   2 Gb/S    0  0
DataMig-cmode-02   0a             0  DM-Cisco9506-1:4-11   DM-Cisco9506-1:2-24   AO  INU  50060e801046b968  2   2 Gb/S    0  0
DataMig-cmode-02   0b             0  DM-Cisco9506-2:4-11   DM-Cisco9506-2:2-24   AO  INU  50060e801046b96c  2   2 Gb/S    0  0
DataMig-cmode-02   0b             0  DM-Cisco9506-2:4-11   DM-Cisco9506-2:1-14   AO  INU  50060e801046b964  1   2 Gb/S    0  0
DataMig-cmode-02   0a             0  DM-Cisco9506-1:4-11   DM-Cisco9506-1:1-14   AO  INU  50060e801046b960  1   2 Gb/S    0  0

Errors:
-

DataMig-cmode::*>
----


. Markieren Sie die Quell-LUN mithilfe der Seriennummer als fremd:
+
storage disk set-foreign-lun { -serial-number 83017542001A } -is-foreign true

+
.. Prüfen Sie, ob die Quell-LUN als fremd gekennzeichnet ist:
+
storage disk show -array-name HITACHI_DF600F_1

.. Liste aller externen Arrays und ihrer Seriennummern:
+
storage disk show -container-type foreign -fields serial-number

+

NOTE: Der LUN create Befehl erkennt die Größe und Ausrichtung auf Basis des Partitionoffsets und erstellt die LUN entsprechend mit dem Argument „ausländischen Festplatte“.



. Zielvolume erstellen:
+
vol create -vserver datamig flivol aggr1 -size 10g

. Erstellen Sie eine Test-LUN mithilfe einer externen LUN:
+
lun create -vserver datamig -path /vol/flivol/testlun1 -ostype linux -foreign-disk 83017542001A

+
.. Listen Sie die Test-LUN auf und überprüfen Sie die Größe der LUN mit der Quell-LUN:
+
lun show

+

NOTE: Für FLI-Offline-Migration muss die LUN online sein, um sie einer Initiatorgruppe zuzuordnen. Die LUN muss dann offline sein, bevor die LUN-Importbeziehung erstellt wird.



. Erstellen Sie eine Test-Initiatorgruppe des Protokolls FCP, ohne Initiatoren hinzuzufügen:
+
lun igroup create -vserver datamig -igroup testig1 -protocol fcp -ostype linux

. Ordnen Sie die Test-LUN der Test-Initiatorgruppe zu:
+
lun map -vserver datamig -path /vol/flivol/testlun1 -igroup testig1

. Test-LUN offline schalten:
+
lun offline -vserver datamig -path /vol/flivol/testlun1

. Importbeziehung mit Test-LUN und Fremd-LUN erstellen:
+
lun import create -vserver datamig -path /vol/flivol/testlun1 -foreign-disk 83017542001A

. Starten Sie die Migration (Import):
+
lun import start -vserver datamig -path /vol/flivol/testlun1

+
.. Überwachen Sie den Importfortschritt:
+
lun import show -vserver datamig -path /vol/flivol/testlun1

.. Prüfen Sie, ob der Importvorgang erfolgreich abgeschlossen wurde:
+
lun import show -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           import    started
                                                           completed     100
----


. Starten Sie den Überprüfungsauftrag, um Quell- und Ziel-LUNs zu vergleichen. Überwachen Sie den Überprüfungsfortschritt:
+
lun import verify start -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
DataMig-cmode::*> lun import show -vserver datamig -path /vol/flivol/testlun1
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           verify    started
                                                           in_progress     44
----
+
.. Prüfen Sie, ob der Verifizierungsauftrag ohne Fehler abgeschlossen wurde:
+
lun import show -vserver datamig -path /vol/flivol/testlun1

+
[listing]
----
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542001A   /vol/flivol/testlun1
                                           verify    started
                                                           completed      100
----


. Löschen Sie die Importbeziehung, um den Migrationsauftrag zu entfernen:
+
lun import delete -vserver datamig -path /vol/flivol/testlun1

+
lun import show -vserver datamig -path /vol/flivol/testlun1

. Die Test-LUN aus der Test-Initiatorgruppe unzuordnen:
+
lun unmap -vserver datamig -path /vol/flivol/testlun1 -igroup testig1

. Test-LUN online schalten:
+
lun online -vserver datamig -path /vol/flivol/testlun1

. Setzen Sie das Attribut „externe LUN“ auf „false“:
+
storage disk modify -serial-number 83017542001A -is-foreign false

+

NOTE: Entfernen Sie nicht die auf dem Quellspeicher erstellte Host-Gruppe mit ONTAP-Initiator-Ports. Dieselbe Host-Gruppe wird bei Migrationen aus diesem Quell-Array wiederverwendet.

. Test-LUN aus dem Quell-Storage entfernen.
+
.. Melden Sie sich als System bei Hitachi Storage Navigator Modular an.
.. Wählen Sie *AMS 2100 array* aus und klicken Sie auf *Array anzeigen und konfigurieren*.
.. Melden Sie sich mit  `root` an.
.. Wählen Sie *Gruppen* und dann *Host Groups*.
.. Wählen Sie *cDOT_FLI Igroup* aus und klicken Sie auf *Host Group bearbeiten*.
.. Im Fenster „Hostgruppe bearbeiten“ wählen Sie alle Zielports aus, die der Test-LUN zugeordnet werden sollen, und wählen Sie *Erzwungenes Festlegen auf alle ausgewählten Ports*.
.. Wählen Sie die Registerkarte *logische Einheiten*.
.. Wählen Sie im Fenster *zugewiesene logische Einheiten* die Test-LUN aus.
.. Wählen Sie *Entfernen*, um die LUN-Zuordnung zu entfernen.
.. Klicken Sie auf *OK*.


. Entfernen Sie nicht die Host-Gruppe, und löschen Sie die Test-LUN nicht weiter.
+
.. Wählen Sie *Logische Einheiten* aus.
.. Wählen Sie die im vorherigen Schritt erstellte Test-LUN aus.
.. Klicken Sie auf *LUN löschen*.
.. Klicken Sie auf *Bestätigen*, um die Test-LUN zu löschen.


. Löschen Sie die Test-LUN auf dem Ziel-Storage.
+
.. Melden Sie sich am ONTAP-Speicher über SSH mit dem  `admin` Benutzer an.
.. Offline-Schaltung der Test-LUN auf dem NetApp Speichersystem:
+
lun offline -vserver datamig -path /vol/flivol/testlun1

+

NOTE: Stellen Sie sicher, dass Sie keine andere Host-LUN auswählen.

.. Zerstöre die Test-LUN auf dem NetApp Speichersystem:
+
lun destroy -vserver datamig -path /vol/flivol/testlun1

.. Offline-Schaltung des Testvolumes auf dem NetApp Speichersystem:
+
vol offline -vserver datamig -volume flivol

.. Zerstören Sie das Testvolume auf dem NetApp Speichersystem:
+
vol zerstören -vserver datamig -volume flivol




