---
permalink: san-migration/reference_site_survey_and_planning_worksheet_source_storage_devices_tab.html 
sidebar: sidebar 
keywords: site, survey and planning worksheet, source storage devices tab 
summary: Als Teil Ihres Arbeitsblatts für die Standortbefragung und -Planung sollten Sie über eine Registerkarte verfügen, die Informationen zu den Storage-Geräten Ihrer Migrationsquelle enthält. 
---
= Registerkarte Quellspeichergeräte für Standortbefragungen und -Planung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Als Teil Ihres Arbeitsblatts für die Standortbefragung und -Planung sollten Sie über eine Registerkarte verfügen, die Informationen zu den Storage-Geräten Ihrer Migrationsquelle enthält.

Das folgende Beispiel zeigt, wie Sie die Registerkarte Quellspeichergeräte einrichten.

|===
5+| Storage-Systeme 


 a| 
Array-Name
 a| 
IP-Adresse
 a| 
Anbieter
 a| 
Array-Modell
 a| 
Microcode FW/ONTAP



 a| 
AMS2100
 a| 
10.x.x.x
 a| 
Hitachi
 a| 
AMS 2100
 a| 
0893/B-X



 a| 
AMS2100
 a| 
10.x.x.x
 a| 
Hitachi
 a| 
AMS 2100
 a| 
0893/B-X



 a| 
AMS2100
 a| 
10.x.x.x
 a| 
Hitachi
 a| 
AMS 2100
 a| 
0893/B-X



 a| 
AMS2100
 a| 
10.x.x.x
 a| 
Hitachi
 a| 
AMS 2100
 a| 
0893/B-X

|===
|===
5+| Storage-Systeme 


 a| 
Controller/Node
 a| 
Port-Name
 a| 
WWPN
 a| 
Fabric-Name
 a| 
Zieltyp



 a| 
Controller 0
 a| 
0 a
 a| 
50060E80xxxxxxxx
 a| 
Produktion Fabric A
 a| 
Quelle



 a| 
Controller 0
 a| 
0e
 a| 
50060E80xxxxxxxx
 a| 
ProduktionsFabric B
 a| 
Quelle



 a| 
Kontroller1
 a| 
1a
 a| 
50060E80xxxxxxxx
 a| 
Produktion Fabric A
 a| 
Quelle



 a| 
Kontroller1
 a| 
1e
 a| 
50060E80xxxxxxxx
 a| 
Produktion Fabric A
 a| 
Quelle

|===