---
permalink: san-migration/reference_site_survey_and_planning_worksheet_storage_groups_tab.html 
sidebar: sidebar 
keywords: site, survey and planning worksheet, storage groups tab 
summary: Als Teil Ihres Arbeitsblatts zur Standortumfrage und -Planung sollten Sie über eine Registerkarte verfügen, die Informationen zu Ihren Speichergruppen enthält. 
---
= Registerkarte Speichergruppen des Arbeitsblatts „Standortbefragung und -Planung“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Als Teil Ihres Arbeitsblatts zur Standortumfrage und -Planung sollten Sie über eine Registerkarte verfügen, die Informationen zu Ihren Speichergruppen enthält.

Das folgende Beispiel zeigt, wie Sie die Registerkarte Speichergruppen einrichten.

|===
4+| Storage-Gruppen 


 a| 
Quelle
 a| 
Ziel



 a| 
Host-Name
 a| 
Storage Group Zur Verfügung
 a| 
WWPN
 a| 
Initiatorgruppenbefehle



 a| 
dm-rx200s6-21
 a| 
dm-rx200s6-21
 a| 
21:00:00:24:ff:30:14:c521:00:00:24:ff:30:14:c4
 a| 
`igroup create -ostype` windows `-protocol` fcp `-vserver` Datendatum `-igroup` dm-rx200s6-21 `-initiator` 21:00:00:24:ff:30:14:c4.21:00:00:24:ff:30:14:c5



 a| 
dm-rx200s6-22
 a| 
dm-rx200s6-22
 a| 
21:00:00:24:ff:30:04:8521:00:00:24:ff:30:04:84
 a| 
`igroup create -ostype` linux `-protocol` fcp `-vserver` Datendatum `-igroup` dm-rx200s6-22 `-initiator` 21:00:00:24:ff:30:04:85,21:00:00:24:ff:30:04:84



 a| 
dm-rx200s6-20
 a| 
dm-rx200s6-20
 a| 
21:00:00:24:ff:30:03:ea21:00:00:24:ff:30:03:eb
 a| 
`igroup create -ostype` vmware `-protocol` fcp `-vserver` Datendatum -`igroup` dm-rx200s6-20 `-initiator` 21:00:00:24:ff:30:03:ea,21:00:00:24:ff:30:03:eb

|===