---
permalink: san-migration/concept_target_and_initiator_port_zoning.html 
sidebar: sidebar 
keywords: target, initiator, port, zoning 
summary: Für die FLI-Migration ist ein Zugriff auf Quell-Storage LUNs durch NetApp Storage erforderlich. Dies wird durch das Zoning von Ziel-Ports des Quell-Storage mit Initiator-Ports des Ziel-Storage erreicht. 
---
= Ziel- und Initiator-Port-Zoning für ONTAP FLI-Migrationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die FLI-Migration ist der Zugriff auf die Quell-LUNs des Fremdarrays durch NetApp -Speicher erforderlich. Dies wird durch die Zoning der Zielports des Quellspeichers mit den Initiatorports des NetApp -Zielspeichers erreicht.

Die vorhandenen Quell-Storage-zu-Host-Zonen werden nicht verändert und nach der Migration deaktiviert. Host-zu-Ziel-Storage-Zonen werden erstellt, um den Zugriff der migrierten LUNs vom Ziel-Storage durch den Host zu ermöglichen.

Für ein Standardmigrationsszenario, das FLI verwendet, sind vier unterschiedliche Zonen erforderlich:

* Zone 1: Quell-Storage auf Ziel-Storage (Produktions-Fabric A)
* Zone 2: Quell-Storage auf Ziel-Storage (Produktions-Fabric B)
* Zone 3: Host-zu-Ziel-Storage (Produktionsstruktur A)
* Zone 4: Host-to-Ziel-Storage (Produktions-Fabric B)


Folgen Sie den folgenden Best Practices für das Zoning:

* Verwenden Sie keine Quell-Storage-Ziel-Ports und Ziel-Storage-Ziel-Ports in derselben Zone.
* Kombinieren Sie keine Ziel-Storage-Initiator-Ports und Host-Ports in derselben Zone.
* Setzen Sie keine Ziel-Storage-Ziel- und Initiator-Ports in derselben Zone zusammen.
* Weisen Sie aus Redundanzgründen mindestens zwei Ports von jedem Controller auf.
* NetApp empfiehlt Single Initiator und Single Target Zoning.


[NOTE]
====
Nach dem Zoning der Ziel-Storage-Ziel-Ports mit den Ziel-Storage-Initiator-Ports wird der Quell-Storage mit dem Befehl show des Storage-Arrays im Ziel-Storage angezeigt.Wenn das Storage-Array zum ersten Mal erkannt wird, werden die NetApp Controller das Array möglicherweise nicht automatisch anzeigen. Beheben Sie dies durch Zurücksetzen des Switch-Ports, an dem ONTAP-Initiator-Ports verbunden sind.

====
Für ein Standardmigrationsszenario, das FLI verwendet, sind vier unterschiedliche Zonen erforderlich. Sie sollten in jede Zone bestimmte Ports einbeziehen.

* Zone 1: Quell-Storage auf Ziel-Storage (Produktions-Fabric A)
+
Zone 1 sollte alle Ziel-Storage-Initiatoren auf allen Nodes und alle Quell-Storage-Ziel-Ports in Fabric A enthalten Zu den Zonenmitgliedern gehören:

+
** ONTAP -- Node1 -- 0a
** ONTAP -- Node2 -- 0a
** AMS2100 -- Ctrl0 -- 0a
** AMS2100 -- Ctrl1 -- 1a


* Zone 2: Quell-Storage auf Ziel-Storage (Produktions-Fabric B)
+
Zone 2 sollte alle Ziel-Storage-Initiator-Ports auf allen Nodes und alle Quell-Storage-Ziel-Ports in Fabric B enthalten Zu den Mitgliedern der Zone 2 gehören:

+
** ONTAP -- Node1 -- 0b
** ONTAP -- Node2 -- 0b
** AMS2100 -- Ctrl0 -- 0e
** AMS2100 -- Ctrl1 -- 1e


* Zone 3: Host-zu-Ziel-Storage (Produktionsstruktur A)
+
Zone 3 sollte den Host Bus Adapter (HBA) Port 1 und die Ziel-Controller-Ports in Produktionsgewebe A enthalten Zu den Mitgliedern der Zone 3 zählen:

+
** ONTAP -- lif1
** ONTAP -- Lif3
** Host -- HBA0


* Zone 4: Host-to-Ziel-Storage (Produktions-Fabric B)
+
Zone 4 sollte den HBA-Port 2 und die Ziel-Controller-Ports in Produktions-Fabric B enthalten Zu den Mitgliedern der Zone 4 zählen:

+
** ONTAP -- lif2
** ONTAP -- Lif4
** Host -- HBA1



