---
permalink: san-migration/concept_using_fli_to_import_luns_into_all_flash.html 
sidebar: sidebar 
keywords: use, foreign lun import, import luns, aff 
summary: Ab ONTAP 9.1 unterstützt AFF FLI. Mit FLI können Sie LUNs aus anderen Arrays direkt in ONTAP Cluster importieren. 
---
= Importieren von LUNs in AFF mithilfe des Imports fremder LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.1 unterstützt AFF FLI. Mit FLI können Sie LUNs aus anderen Arrays direkt in ONTAP Cluster importieren.

Ab ONTAP 8.3.2 kann AFF FLI mit einem genehmigten Process Variance Request (PVR) unterstützen. Wenden Sie sich an Ihr NetApp Kundenbetreuungsteam, um den PVR zur Genehmigung einzureichen. Nach der Genehmigung erhält der Einreicher, in der Regel ein NetApp -Systemingenieur, ein Genehmigungsschreiben mit Anweisungen zur Aktivierung der FLI-Funktionalität.

Bei ONTAP -Softwareversionen vor 8.3.2 müssen Sie FLI-Importe auf einem Nicht- AFF -HA-Paar auf demselben Cluster wie das AFF durchführen. Nach Abschluss der Migration können Sie dann nicht-unterbrechende Operationen (NDO) wie vol oder LUN move verwenden, um die migrierten LUNs nach AFF zu verschieben. Falls Ihr AFF Cluster keine Nicht- AFF Knoten enthält, sprechen Sie mit Ihrem Account-Team über die Möglichkeit, alternative Hardware auszuleihen, um dies zu ermöglichen.
