---
permalink: san-migration/concept_migration_types_supported_by_foreign_lun_import.html 
sidebar: sidebar 
keywords: migration, types, supported, foreign, lun, import 
summary: 'FLI unterstützt vier Arten von Migrations-Workflows: Online, offline, Transition und automatisiert. Die Wahl des Workflows hängt von der Konfiguration und anderen Faktoren ab.' 
---
= Migrationstypen, die vom Import fremder LUNs unterstützt werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FLI unterstützt vier Arten von Migrations-Workflows: Online, offline, Transition und automatisiert. Die Wahl des Workflows hängt von der Konfiguration und anderen Faktoren ab.

* Bei einer Online-Migration ermöglicht FLI von Arrays anderer Anbieter, dass das Client-System während der Migration online bleiben kann (erfordert ein Windows, Linux oder ESXi Host-Betriebssystem).
* Bei einer Offline-Migration stellt FLI von Arrays anderer Anbieter das Client-System offline und kopiert die Daten in die neue LUN, bevor sie wieder in den Online-Modus versetzt werden.
* Bei einer Migration zur FLI wechselt ONTAP im 7-Mode zu ONTAP. Hierbei handelt es sich um denselben Prozess, außer dass das Quell-Array ONTAP ist. Der Übergangsworkflow ist entweder im Online- oder Offline-Modus verfügbar.
* In einer automatisierten Migration nutzt FLI Workflow-Automatisierung (WFA) Software zur Automatisierung von Teilen des Migrationsprozesses. FLI mit WFA ist entweder im Online- oder Offline-Modus verfügbar.


Die Unterschiede zwischen den Workflows müssen bei Umstellungen, Länge des Unterbrechungsfensters und Automatisierung auftreten oder wenn es sich bei dem Quell-Array um ein NetApp Array mit ONTAP 7-Mode oder ein Drittanbieter-Array handelt.
