---
permalink: san-migration/concept_lun_requirements_and_limitations.html 
sidebar: sidebar 
keywords: lun, requirements, limitations 
summary: Ihre LUNs sollten die folgenden Anforderungen erfüllen, bevor Sie eine FLI-Migration beginnen. 
---
= LUN-Anforderungen und -Einschränkungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ihre LUNs sollten die folgenden Anforderungen erfüllen, bevor Sie eine FLI-Migration beginnen.

* FLI erfordert mindestens einen FC Port auf jedem Controller und LUNS direkt im Initiatormodus.
* Um Zuweisungen von ONTAP zu verhindern, muss die fremde LUN auf dem Ziel-Array als fremd gekennzeichnet werden.
* Die ausländische LUN muss vor Beginn des Imports in einer Importbeziehung stehen.
* Die LUN muss die gleiche Größe wie die fremde LUN haben. Diese Anforderung wird während der LUN-Erstellungsschritte berücksichtigt.
* Die Blockgröße der ausländischen LUN muss 512 Byte betragen. NetApp LUNs unterstützen nur eine Blockgröße von 512 Byte.
* Die LUN darf nicht erweitert oder schrumpfend sein.
* Die LUN muss mindestens einer Initiatorgruppe zugeordnet sein.
* Die NetApp LUN sollte offline genommen werden, bevor eine Verbindung hergestellt wird. Sobald die LUN-Beziehung hergestellt ist, kann sie im Falle von Online-FLI wieder online geschaltet werden.




== Einschränkungen

* Alle Migrationen sind auf LUN-Ebene durchgeführt.
* FLI unterstützt nur Fibre Channel-Verbindungen (FC).
* ISCSI-Verbindungen werden nicht direkt von FLI unterstützt. Damit iSCSI LUNs mithilfe von FLI migriert werden können, muss der LUN-Typ zu FC geändert werden. Nach Abschluss der Migration wird der LUN-Typ wieder in iSCSI geändert.

