---
permalink: san-migration/create-lun-import-relationship-online.html 
sidebar: sidebar 
keywords: fli online, prepare, lun path 
summary: Bevor Sie eine LUN von einem fremden Array auf einen ONTAP Speicher migrieren können, müssen Sie eine LUN-Importbeziehung erstellen. Eine LUN-Importbeziehung ist eine dauerhafte Verbindung zwischen Quell- und Zielspeicher zum Zweck des Datenimports. 
---
= Erstellen der LUN-Importbeziehung für eine ONTAP FLI-Onlinemigration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie eine LUN von einem fremden Array auf einen ONTAP Speicher migrieren können, müssen Sie eine LUN-Importbeziehung erstellen. Eine LUN-Importbeziehung ist eine dauerhafte Verbindung zwischen Quell- und Zielspeicher zum Zweck des Datenimports. Quell- und Zielendpunkte sind LUNs.

Das Erstellen der LUN-Importbeziehung für Online-Migrationen zum Importieren von Fremd-LUNs (FLI) umfasst das Identifizieren der aus dem Quell-Array zu importierenden Fremd-LUN, das Erstellen und Konfigurieren eines Zielvolumes zur Aufnahme der Fremd-LUN, das Erstellen der Ziel-LUN und schließlich das Herstellen der Importbeziehung.



== Schritt 1: Identifizieren Sie die Quell-Array-LUN als Fremd-LUN in ONTAP

Sie müssen die Quell-Array-LUN als fremde LUN identifizieren, bevor Sie mit der FLI-Onlinemigration beginnen.

.Schritte
. Ändern Sie in ONTAP die Berechtigungsstufe auf „Erweitert“.
+
[source, cli]
----
set -privilege advanced
----
. Eingabe `y` Wenn Sie gefragt werden, ob Sie fortfahren möchten.
. Vergewissern Sie sich, dass das Quell-Array auf dem Ziel-Controller angezeigt wird.
+
[source, cli]
----
storage array show
----
+
Das folgende Beispiel zeigt die Erkennung eines DGC LUNZ-Arrays.

+
[listing]
----
cluster::*> storage array show
Prefix                         Name   Vendor            Model Options
-------- ---------------------------- -------- ---------------- ----------
DGC-1                      DGC_LUNZ_1      DGC             LUNZ
1 entries were displayed.
----
. Zeigt Details zur Quell-LUN an.
+
[source, cli]
----
storage array config show -array-name <array_name> -instance
----
+
Das folgende Beispiel zeigt die Details des DGC LUNZ-Arrays.

+
[listing]
----
cluster::*> storage array config show -array-name DGC_LUNZ_1 -instance

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 0
        Array Target Ports: 500601643ea067da
                 Initiator: 0c
                Array Name: DGC_LUNZ_1
   Target Side Switch Port: stme-5010-3:2-1
Initiator Side Switch Port: stme-5010-3:2-3
      Number of array LUNs: 1

           Controller Name: ontaptme-fc-cluster-01
                 LUN Group: 0
        Array Target Ports: 500601653ea067da
                 Initiator: 0d
                Array Name: DGC_LUNZ_1
   Target Side Switch Port: stme-5010-4:2-1
Initiator Side Switch Port: stme-5010-4:2-3
      Number of array LUNs: 1
~~~~~~~~~~~ output truncated for readability ~~~~~~~~~~~~~~~~~
8 entries were displayed.
----
. Vergewissern Sie sich, dass das Quell-Array über alle Initiator-Ports erkannt wird.
+
[source, cli]
----
storage array config show -array-name <array_name>
----
+
Das folgende Beispiel zeigt das DGC LUNZ-Array, das über alle Initiator-Ports erkannt wurde.

+
[listing]
----
cluster::*> storage array config show -array-name DGC_LUNZ_1
             LUN   LUN
Node         Group Count                   Array Name       Array Target Port Initiator
------------ ----- ----- ---------------------------- ----------------------- ---------
ontaptme-fc-cluster-01
                 0     1                   DGC_LUNZ_1        500601643ea067da        0c
                                                             500601653ea067da        0d
                                                             5006016c3ea067da        0c
                                                             5006016d3ea067da        0d
ontaptme-fc-cluster-02
                 0     1                   DGC_LUNZ_1        500601643ea067da        0c
                                                             500601653ea067da        0d
                                                             5006016c3ea067da        0c
                                                             5006016d3ea067da        0d
8 entries were displayed.
----
. Listen Sie die vom Quellspeicher zugeordneten LUNs auf und überprüfen Sie dann die Datenträgereigenschaften und -pfade.
+
[source, cli]
----
storage disk show -array-name <array_name> -container-type lun
----
+
Das folgende Beispiel zeigt die vom Quellspeicher zugeordneten LUNs.

+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1 -instance
                  Disk: DGC-1.9
        Container Type: unassigned
            Owner/Home: -  / -
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: DGC_LUNZ_1
                Vendor: DGC
                 Model: VRAID
         Serial Number: 600601603F103100662E70861000E511
                   UID: 60060160:3F103100:662E7086:1000E511:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: -
              Position: present
Checksum Compatibility: block
             Aggregate: -
                  Plex: -
Paths:
                               LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
ontaptme-fc-cluster-02
                   0c             0  stme-5010-3:2-4       stme-5010-3:2-2       AO  INU  5006016c3ea067da              2   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-2       AO  INU  5006016d3ea067da              2   4 Gb/S             0             0
ontaptme-fc-cluster-02
                   0d             0  stme-5010-4:2-4       stme-5010-4:2-1       ANO RDY  500601653ea067da              1   4 Gb/S             0             0

Errors:
-
----
. Zeigen Sie die Quell-LUN an.
+
[source, cli]
----
storage disk show -array-name <array_name>
----
+
Das folgende Beispiel zeigt die Quell-LUN.

+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
DGC-1.9                   -     -   - LUN     unassigned  -         -
----
. Markieren Sie die Quell-LUN als „fremd“.
+
[source, cli]
----
storage disk set-foreign-lun -is-foreign true -disk <disk_name>
----
+
Das folgende Beispiel zeigt den Befehl zum Markieren der Quell-LUN als fremd.

+
[listing]
----
cluster::*> storage disk set-foreign-lun -is-foreign true -disk DGC-1.9
----
. Vergewissern Sie sich, dass die Quell-LUN als „Foreign“ gekennzeichnet ist.
+
[source, cli]
----
storage disk show -array-name <array_name>
----
+
Das folgende Beispiel zeigt die als fremd markierte Quell-LUN.

+
[listing]
----
cluster::*> storage disk show -array-name DGC_LUNZ_1
                     Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
DGC-1.9
----
. Listen Sie alle fremden LUNs und ihre Seriennummern auf.
+
[source, cli]
----
storage disk show -container-type foreign -fields serial-number
----
+
Seriennummern werden in FLI LUN-Importbefehlen verwendet.

+
Das folgende Beispiel zeigt die fremde LUN und ihre Seriennummer.

+
[listing]
----
disk    serial-number
------- --------------------------------
DGC-1.9 600601603F103100662E70861000E511
----




== Schritt 2: Erstellen und Konfigurieren eines Zielvolumes

Bevor Sie die LUN-Importbeziehung für eine FLI-Onlinemigration erstellen, müssen Sie auf Ihrem ONTAP Speichersystem ein Volume erstellen, das die LUN enthält, die Sie aus Ihrem Fremd-Array importieren.

.Informationen zu diesem Vorgang
Ab ONTAP 9.17.1 wird die Datenmigration fremder LUNs mithilfe der FLI-Online-Migration mit ASA r2-Systemen unterstützt. ASA r2-Systeme unterscheiden sich von anderen ONTAP Systemen (ASA, AFF und FAS) in der Implementierung ihrer Speicherschicht. In ASA r2-Systemen werden Volumes automatisch erstellt, wenn eine Speichereinheit (LUN oder Namespace) erstellt wird. Daher müssen Sie vor dem Erstellen der LUN-Importbeziehung kein Volume erstellen. Sie können diesen Schritt überspringen, wenn Sie ein ASA r2-System verwenden.

Erfahren Sie mehr über link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2-Systeme"^] .

.Schritte
. Erstellen eines Ziel-Volumes
+
[source, cli]
----
volume create -vserver <SVM_name> -volume <volume_name> -aggregate <aggregate_name> -size <size>
----
. Überprüfen Sie, ob das Volume erstellt wurde.
+
[source, cli]
----
volume show -vserver <SVM_name>
----
+
Das folgende Beispiel zeigt das im *fli*-SVM erstellte *fli_vol*-Volume.

+
[listing]
----
cluster::*> vol show -vserver fli
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
fli       fli_root     aggr1        online     RW          1GB    972.6MB    5%
fli       fli_vol      aggr1        online     RW          2TB     1.90TB    5%
2 entries were displayed.
----
. Legen Sie für jedes Volume die Option Fraktive_reserveOption auf fest `0` Und legen Sie die Snapshot-Richtlinie auf fest `none`.
+
[source, cli]
----
volume modify -vserver <SVM_name> -volume * -fractional-reserve 0 -snapshot-policy none
----
. Überprüfen Sie die Lautstärkeeinstellungen.
+
[source, cli]
----
volume show -vserver <SVM_name> -volume * -fields fractional-reserve,snapshot-policy
----
+
Das folgende Beispiel zeigt die *Fractional-Reserve*-Einstellung auf  `0` und die *Snapshot-Richtlinie* eingestellt auf  `none` für das *fli_vol*-Volume im *fli*-SVM.

+
[listing]
----
cluster::*> vol show -vserver datamig -volume * -fields fractional-reserve,snapshot-policy
vservervolumesnapshot-policyfractional-reserve
-----------------------------------------------
datamigdatamig_rootnone0%
datamigwinvolnone0%
Volume modify successful on volume winvol of Vserver datamig.
----
. Löschen vorhandener Snapshot Kopien
+
[source, cli]
----
set advanced; snap delete –vserver <SVM_name> –vol <volume_name> –snapshot * -force true
----
+
[NOTE]
====
Bei der FLI-Migration wird jeder Block der Ziel-LUNs geändert. Wenn vor der FLI-Migration Standard- oder andere Snapshot-Kopien auf einem Volume vorhanden sind, wird das Volume gefüllt. Das Ändern der Richtlinie und das Entfernen vorhandener Snapshot Kopien vor der FLI-Migration ist erforderlich. Snapshot-Richtlinien können nach der Migration erneut festgelegt werden.

====




== Schritt 3: Erstellen der Ziel-LUN und der LUN-Importbeziehung

Um Ihren Fremd-LUN-Import vorzubereiten, erstellen Sie die Ziel-LUN und die Ziel-Igroup, ordnen Sie die LUN der Igroup zu und erstellen Sie die LUN-Importbeziehung.

Ab ONTAP 9.17.1 wird die Datenmigration von fremden LUNs mit FLI-Offline-Migration unterstützt mitlink:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2-Systeme"^]. ASA r2-Systeme unterscheiden sich von anderen ONTAP Systemen (ASA, AFF und FAS) in der Implementierung ihrer Speicherschicht. In ASA r2-Systemen werden Volumes automatisch erstellt, wenn eine Speichereinheit (LUN oder Namespace) erstellt wird. Volume enthält nur eine Speichereinheit. Daher müssen Sie bei ASA r2-Systemen den Volumenamen nicht in die  `-path` Option beim Erstellen der LUN. Sie sollten stattdessen den Pfad der Speichereinheit einschließen.

.Schritte
. Erstellen Sie die Ziel-LUN.
+
[source, cli]
----
lun create -vserver <SVM_name> -path <volume_path|storage_unit_path> -ostype <os_type> -foreign-disk <serial_number>
----
+
[NOTE]
====
Der  `lun create` Der Befehl ermittelt die LUN-Größe und -Ausrichtung anhand des Partitionsoffsets und erstellt die LUN entsprechend mit der Option „Foreign-Disk“. Einige I/O-Vorgänge erscheinen immer als partielle Schreibvorgänge und wirken daher falsch ausgerichtet. Beispiele hierfür sind Datenbankprotokolle.

====
. Überprüfen Sie, ob die neue LUN erstellt wurde.
+
[source, cli]
----
lun show -vserver <SVM_name>
----
+
Das folgende Beispiel zeigt die neue LUN, die im *fli*-SVM erstellt wurde.

+
[listing]
----
cluster::*> lun show -vserver fli
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
fli       /vol/fli_vol/OnlineFLI_LUN      online  unmapped windows_2008  1TB
----
. Wenn Sie ONTAP 9.15.1 oder höher ausführen, deaktivieren Sie die Speicherplatzzuweisung für die neu erstellten LUNs.
+
Die Speicherplatzzuweisung ist für neu erstellte LUNs in ONTAP 9.15.1 und höher standardmäßig aktiviert.

+
[source, cli]
----
lun modify -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -space-allocation disabled
----
. Stellen Sie sicher, dass die Speicherplatzzuweisung deaktiviert ist.
+
[source, cli]
----
lun show -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -fields space-allocation
----
. Erstellen einer Initiatorgruppe des FCP-Protokolls mit Host-Initiatoren.
+
[source, cli]
----
igroup create -vserver <SVM_name> -igroup <igroup_name> -protocol fcp -ostype <os_type> -initiator <initiator_name>
----
. Überprüfen Sie, ob der Host auf alle Pfade zur neuen Igroup zugreifen kann.
+
[source, cli]
----
igroup show -vserver <SVM_name> -igroup <igroup_name>
----
+
Das folgende Beispiel zeigt die *FLI*-Igroup im *fli*-SVM mit zwei angemeldeten Initiatoren.

+
[listing]
----
cluster::*> igroup show –vserver fli –igroup FLI
   Vserver name: fli
    Igroup name: FLI
       Protocol: fcp
     OS Type: Windows
Portset Binding Igroup: -
   Igroup UUID: 5c664f48-0017-11e5-877f-00a0981cc318
          ALUA: true
    Initiators: 10:00:00:00:c9:e6:e2:77 (logged in)
10:00:00:00:c9:e6:e2:79 (logged in)
----
. Offline der Ziel-LUN.
+
[source, cli]
----
lun offline -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Das folgende Beispiel zeigt den Befehl zum Offline-Schalten der neuen LUN im *fli*-SVM.

+
[listing]
----
cluster::*> lun offline -vserver fli -path /vol/fli_vol/OnlineFLI_LUN

Warning: This command will take LUN "/vol/fli_vol/OnlineFLI_LUN" in Vserver "fli" offline.
Do you want to continue? {y|n}: y
----
. Ordnen Sie die Ziel-LUN der Initiatorgruppe zu.
+
[source, cli]
----
lun map -vserver <SVM_name> -path <volume_path|storage_unit_path> -igroup <igroup_name>
----
. Importbeziehung zwischen neuer LUN und ausländischer LUN erstellen.
+
[source, cli]
----
lun import create -vserver <SVM_name> -path <volume_path|storage_unit_path> -foreign-disk <disk_serial_number>
----


.Wie geht es weiter?
link:map-source-lun-to-destination-online-migration.html["Ordnen Sie die Quell-LUN der ONTAP -Ziel-LUN zu"] .

.Ähnliche Informationen
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_is_an_unaligned_I%2F%2FO%3F["Erfahren Sie mehr über nicht ausgerichtete E/A"^] .
