---
permalink: san-migration/remove-lun-import-relationship-online.html 
sidebar: sidebar 
keywords: clean up, fli, online migration 
summary: Nach Abschluss der FLI-Online-Migration entfernen Sie die LUN-Importbeziehung. 
---
= Entfernen der LUN-Importbeziehung nach einer ONTAP FLI-Onlinemigration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach Abschluss der Online-Migration des Foreign LUN Import (FLI) kann die LUN-Importbeziehung sicher entfernt werden. Der Host greift nun für alle E/A-Vorgänge auf das neue NetApp Array zur neuen ONTAP LUN zu, und die Quell-LUN wird nicht mehr verwendet.

Ab ONTAP 9.17.1 wird die Datenmigration von fremden LUNs mit FLI-Offline-Migration unterstützt mitlink:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2-Systeme"^]. ASA r2-Systeme unterscheiden sich von anderen ONTAP Systemen (ASA, AFF und FAS) in der Implementierung ihrer Speicherschicht. In ASA r2-Systemen werden Volumes automatisch erstellt, wenn eine Speichereinheit (LUN oder Namespace) erstellt wird. Volume enthält nur eine Speichereinheit. Daher müssen Sie bei ASA r2-Systemen den Volumenamen nicht in die  `-path` Option beim Erstellen der LUN. Sie sollten stattdessen den Pfad der Speichereinheit einschließen.

.Schritte
. Löschen Sie die LUN-Importbeziehung.
+
[source, cli]
----
lun import delete -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
. Stellen Sie sicher, dass die Importbeziehung gelöscht ist.
+
[source, cli]
----
lun import show -vserver <SVM_name>
----
. Zeigen Sie optional das Ereignisprotokoll an, um die Migrationsergebnisse zu überprüfen.
+
[source, cli]
----
event log show –event fli*
----
+
Dieses Beispiel zeigt die Beispielausgabe des Befehls zum Anzeigen des Ereignisprotokolls für FLI-Migrationsergebnisse.

+
[listing]
----
DataMig-ontap::*> event log  show –event fli*

7/7/2014 18:37:21   DataMig-ontap-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 83017542001E of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiS is successfully completed.
7/7/2014 18:37:15   DataMig-ontap-01 INFORMATIONAL fli.lun.verify.complete: Import verify of foreign LUN 830175420015 of size 42949672960 bytes from array model DF600F belonging to vendor HITACHI  with NetApp LUN QvChd+EUXoiX is successfully completed.
7/7/2014 18:02:21   DataMig-ontap-01 INFORMATIONAL fli.lun.import.complete: Import of foreign LUN 83017542000F of size 3221225472 bytes from array model DF600F belonging to vendor HITACHI  is successfully completed. Destination NetApp LUN is QvChd+EUXoiU.
----


.Wie geht es weiter?
link:concept_fli_online_post_migration_tasks.html["Ausführen von Aufgaben nach der Migration"] .
