---
permalink: san-migration/task_fli_offline_importing_the_data.html 
sidebar: sidebar 
keywords: fli offline, import data 
summary: In diesen Schritten wird beschrieben, wie die Daten aus der Quell-LUN in die Ziel-LUN importiert werden. 
---
= FLI offline: Importieren der Daten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In diesen Schritten wird beschrieben, wie die Daten aus der Quell-LUN in die Ziel-LUN importiert werden.

.Schritte
. Starten Sie den Migrationsimport.
+
[listing]
----
DataMig-cmode::*> lun import start –vserver datamig –path /vol/winvol/bootlun

DataMig-cmode::*> lun import start –vserver datamig –path /vol/winvol/fdrive

DataMig-cmode::*> lun import start –vserver datamig –path /vol/winvol/gdrive
----
. Überwachen Sie den Importfortschritt. Vergleichen Sie den Fortschritt, den Sie hier sehen, mit den Schätzungen der Migrations-Performance, die Sie nach der Durchführung Ihrer Testmigrationen entwickelt haben.
+
[listing]
----
DataMig-cmode::*> lun import show –vserver datamig –fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration
vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     completed         100              4194304         4194304      -
datamig 83017542000F /vol/winvol/gdrive started     completed         100              6291456         6291456      -
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       83               35107077        41943040     00:00:48
3 entries were displayed.
----
. Überprüfen Sie, ob der Importauftrag erfolgreich abgeschlossen wurde.
+
[listing]
----
DataMig-cmode::*> lun import show –vserver datamig –fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration
vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     completed         100              4194304         4194304      -
datamig 83017542000F /vol/winvol/gdrive started     completed         100              6291456         6291456      -
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     completed         100
3 entries were displayed.
----

