---
permalink: san-migration/task_fli_offline_verifying_migration_results.html 
sidebar: sidebar 
keywords: fli offline, verify, migration, results 
summary: Ein Verifizierungsjob ist optional, wird aber empfohlen. Es handelt sich um einen Block-für-Block-Vergleich der Quell- und Ziel-LUNs. Überprüfen Sie, dass Jobs fast gleich oder etwas länger dauern als die Migrationszeit. 
---
= Überprüfen der Ergebnisse der ONTAP FLI-Offlinemigration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem eine LUN vom Fremd-Array auf Ihr ONTAP Speichersystem migriert wurde, kann FLI einen Block-für-Block-Vergleich der Quell- und Ziel-LUNs durchführen, um die Vollständigkeit und Genauigkeit der Migration zu überprüfen. Eine Migrationsüberprüfung dauert ungefähr genauso lange wie die eigentliche Migration (oder etwas länger).

Eine Migrationsüberprüfung ist nicht erforderlich, wird jedoch dringend empfohlen.

.Informationen zu diesem Vorgang
Ab ONTAP 9.17.1 wird die Datenmigration von fremden LUNs mit FLI-Offline-Migration unterstützt mitlink:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2-Systeme"^]. ASA r2-Systeme unterscheiden sich von anderen ONTAP Systemen (ASA, AFF und FAS) in der Implementierung ihrer Speicherschicht. In ASA r2-Systemen werden Volumes automatisch erstellt, wenn eine Speichereinheit (LUN oder Namespace) erstellt wird. Volume enthält nur eine Speichereinheit. Daher müssen Sie bei ASA r2-Systemen den Volumenamen nicht in die  `-path` Option beim Erstellen der LUN. Sie sollten stattdessen den Pfad der Speichereinheit einschließen.

.Schritte
. Starten Sie die Überprüfung der LUN-Migration.
+
[source, cli]
----
lun import verify start -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Dieses Beispiel zeigt den Befehl zum Starten der LUN-Migrationsüberprüfung für LUNs mit den Namen *bootlun*, *fdrive* und *gdrive* im *winvol*-Volume und der *datamig*-SVM.

+
[listing]
----
DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/bootlun

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/fdrive

DataMig-ontap::*> lun import verify start -vserver datamig -path /vol/winvol/gdrive
----
. Überwachen Sie den Verifizierungsstatus.
+
[source, cli]
----
lun import show -vserver <SVM_name> -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, estimated-remaining-duration
----
+
Dieses Beispiel zeigt den Befehl zum Überwachen des Überprüfungsstatus für die *datamig*-SVM.

+
[listing]
----
DataMig-ontap::*> lun import show -vserver datamig -fields vserver, foreign-disk, path, admin-state, operational-state, percent-complete, imported-blocks, total-blocks, , estimated-remaining-duration

vserver foreign-disk path               admin-state operational-state percent-complete imported-blocks total-blocks estimated-remaining-duration
------- ------------ ------------------ ----------- ----------------- ---------------- --------------- ------------ ----------------------------
datamig 83017542000E /vol/winvol/fdrive started     in_progress       57               -               4194304      00:01:19
datamig 83017542000F /vol/winvol/gdrive started     in_progress       40               -               6291456      00:02:44
datamig 830175420010 /vol/linuxvol/bootlun
                                        started     in_progress       8                -               41943040     00:20:29
3 entries were displayed.
----
+
Sie können denselben Befehl ausführen, um den Fortschritt der Überprüfung zu verfolgen. Der Betriebszustand zeigt den Status „Abgeschlossen“ an, wenn der Überprüfungsauftrag erfolgreich abgeschlossen wurde.

. Beenden Sie die LUN-Verifizierung.
+
[source, cli]
----
lun import verify stop -vserver <SVM_name> -path <volume_path|storage_unit_path>
----
+
Dieses Beispiel zeigt den Befehl zum Stoppen der LUN-Verifizierung für die *datamig*-SVM.

+
[listing]
----
DataMig-ontap::*> lun import verify stop -vserver datamig -path /vol/esxvol/winrdmplun
----
+
Die LUN-Importprüfung muss explizit gestoppt werden, bevor die LUN wieder online geschaltet wird. Andernfalls  `lun online` Der Befehl schlägt fehl. Dieser Schritt muss manuell ausgeführt werden, auch wenn der Status anzeigt, dass die Überprüfung abgeschlossen ist.



.Wie geht es weiter?
link:remove-lun-import-relationship-offline.html["Entfernen der LUN-Importbeziehung"] .
