---
permalink: san-migration/task_configuring_migration_jobs.html 
sidebar: sidebar 
keywords: configure, migration, jobs 
summary: Für den FLI Offline Workflow ist die Konfiguration der Quell-LUN und Ziel-LUNs erforderlich. 
---
= Migrationsaufgaben werden konfiguriert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für den FLI Offline Workflow ist die Konfiguration der Quell-LUN und Ziel-LUNs erforderlich.

.Schritte
. Für die FLI-Migration muss die Quell-LUN als fremd gekennzeichnet werden. Markieren Sie die Quell-LUNs mit der Seriennummer als „fremd“.
+
[listing]
----

DataMig-cmode::*> storage disk set-foreign-lun { -serial-number 83017542001E }
                   -is-foreign true
DataMig-cmode::*> storage disk set-foreign-lun { -serial-number 83017542000E }
                   -is-foreign true
DataMig-cmode::*> storage disk set-foreign-lun { -serial-number 83017542000F }
                   -is-foreign true
----
. Vergewissern Sie sich, dass die Quell-LUN als „Foreign“ gekennzeichnet ist.
+
[listing]
----
DataMig-cmode::*> storage disk show -array-name HITACHI_DF600F_1 -fields disk, serial-number, container-type, owner,import-in-progress, is-foreign
disk     owner is-foreign container-type import-in-progress serial-number
-------- ----- ---------- -------------- ------------------ -------------
HIT-1.2  -     true       foreign        false              83017542001E
HIT-1.3  -     true       foreign        false              83017542000E
HIT-1.4  -     true       foreign        false              83017542000F
3 entries were displayed.
----
. Erstellung von Ziel-Volumes
+
[listing]
----
DataMig-cmode::*> vol create -vserver datamig winvol aggr1 -size 100g
[Job 5606] Job succeeded: Successful
----
. Deaktivieren Sie für jedes Volume die standardmäßige Snapshot-Richtlinie. Falls vor der FLI-Migration standardmäßige Snapshot-Kopien vorhanden sind, benötigt das Volume zusätzlichen Speicherplatz zum Speichern geänderter Daten.
+
[listing]
----
DataMig-cmode::> volume modify -vserver datamig -volume winvol -snapshot-policy none

Warning: You are changing the Snapshot policy on volume winvol to none.  Any Snapshot copies on this volume from the previous policy will not be deleted by
         this new Snapshot policy.
Do you want to continue? {y|n}: y
Volume modify successful on volume winvol of Vserver datamig.
----
. Einstellen `fraction_reserveoption` Für jedes Volume bis `0` Und legen Sie die Snapshot-Richtlinie auf fest `none`.
+
[listing]
----
DataMig-cmode::> vol modify -vserver datamig -volume * -fractional-reserve 0 –snapshot-policy none
Volume modify successful on volume winvol of Vserver datamig.
----
. Überprüfen Sie Ihre Lautstärkeeinstellungen.
+
[listing]
----
DataMig-cmode::> vol show -vserver datamig -volume * -fields fractional-reserve,snapshot-policy
vservervolumesnapshot-policyfractional-reserve
-----------------------------------------------
datamig datamig_rootnone0%
datamigwinvolnone0%
Volume modify successful on volume winvol of Vserver datamig.
----
. Löschen vorhandener Snapshot Kopien
+
[listing]
----
DataMig-cmode::> set advanced; snap delete –vserver datamig –vol winvol –snapshot * -force true
1 entry was acted on.
----
+
[NOTE]
====
Bei der FLI-Migration wird jeder Block der Ziel-LUN geändert. Wenn vor der FLI-Migration Standard- oder andere Snapshot-Kopien auf einem Volume vorhanden sind, wird das Volume gefüllt. Eine Änderung der Richtlinie und das Entfernen vorhandener Snapshot Kopien vor der FLI-Migration sind erforderlich. Snapshot-Richtlinien können nach der Migration erneut festgelegt werden.

====
+
[NOTE]
====
Der LUN create-Befehl erkennt Größe und Ausrichtung auf Basis des Partitionsoffsets und erstellt die LUN entsprechend mit Option „Foreign Disk“. Lesen Sie dazu im NetApp Knowledgebase Artikel *Was ist ein nicht ausgerichteter I/O?* beachten Sie auch, dass einige I/O immer partielle Schreibzugriffe erscheinen und daher falsch ausgerichtet sind. Beispiele hierfür sind Datenbank-Logs.

====
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_is_an_unaligned_I%2F%2FO%3F["Was ist ein nicht ausgerichteter I/O?"]

. Erstellen Sie Ziel-LUNs mithilfe der ausländischen LUN.
+
[listing]
----
DataMig-cmode::*> lun create -vserver datamig -path /vol/winvol/bootlun -ostype windows_2008 -foreign-disk 83017542001E

Created a LUN of size 40g (42949672960)

Created a LUN of size 20g (21474836480)
DataMig-cmode::*> lun create -vserver datamig -path /vol/linuxvol/lvmlun1 -ostype linux -foreign-disk 830175420011

Created a LUN of size 2g (2147483648)
DataMig-cmode::*> lun create -vserver datamig -path /vol/esxvol/bootlun -ostype vmware -foreign-disk 830175420014

Created a LUN of size 20g (21474836480)
----
. Listen Sie die Ziel-LUNs auf und überprüfen Sie die Größe der LUN mit Quell-LUN.
+
[listing]
----
DataMig-cmode::*> lun show -vserver datamig
Vserver   Path                            State   Mapped   Type        Size
--------- ------------------------------- ------- -------- -------- --------
datamig   /vol/esxvol/bootlun             online  unmapped vmware       20GB
datamig   /vol/esxvol/linuxrdmvlun        online  unmapped linux         2GB
datamig   /vol/esxvol/solrdmplun          online  unmapped solaris       2GB
datamig   /vol/winvol/gdrive              online  unmapped windows_2008  3GB
4 entries were displayed.

DataMig-cmode::*>
----
+
[NOTE]
====
Für FLI-Offline-Migration muss die LUN der Initiatorgruppe zugeordnet und dann in den Offline-Modus versetzt werden, bevor die LUN-Importbeziehung erstellt wird.

====
. Host igroup des Protokolls FCP erstellen und Initiatoren hinzufügen. Suchen Sie Initiator-WWPNs im Abschnitt „Speichergruppen“ Ihres Planungsarbeitsblatts für die Standortumfrage.
+
[listing]
----
DataMig-cmode::*> lun igroup create -ostype windows -protocol fcp -vserver datamig -igroup dm-rx200s6-21 -initiator 21:00:00:24:ff:30:14:c4,21:00:00:24:ff:30:14:c5

DataMig-cmode::*> lun igroup create -ostype linux -protocol fcp -vserver datamig  -igroup dm-rx200s6-22 -initiator 21:00:00:24:ff:30:04:85,21:00:00:24:ff:30:04:84

DataMig-cmode::*> lun igroup create -ostype vmware -protocol fcp -vserver datamig -igroup dm-rx200s6-20 -initiator 21:00:00:24:ff:30:03:ea,21:00:00:24:ff:30:03:eb
----
+
[NOTE]
====
Verwenden Sie dieselbe LUN-ID wie die Quelle. Beziehen Sie sich auf den Abschnitt Quell-LUNS des Planungsarbeitsblatts für die Standortumfrage.

====
. Ordnen Sie die Ziel-LUNs der Initiatorgruppe zu.
+
[listing]
----
DataMig-cmode::*> lun map -vserver datamig -path /vol/winvol/bootlun -igroup dm-rx200s6-21 -lun-id 0
DataMig-cmode::*> lun map -vserver datamig -path /vol/linuxvol/bootlun -igroup dm-rx200s6-22 -lun-id 0
DataMig-cmode::*> lun map -vserver datamig -path /vol/esxvol/bootlun -igroup dm-rx200s6-20 -lun-id 0
----
. Offline der Ziel-LUNs.
+
[listing]
----
DataMig-cmode::*> lun offline -vserver datamig -path /vol/esxvol/bootlun
DataMig-cmode::*> lun offline -vserver datamig -path /vol/esxvol/linuxrdmvlun
DataMig-cmode::*> lun offline -vserver datamig -path /vol/esxvol/solrdmplun
----
. Importbeziehung mit Ziel-LUN und Quell-LUN erstellen.
+
[listing]
----
DataMig-cmode::*> lun import create -vserver datamig -path /vol/winvol/bootlun -foreign-disk 83017542001E
DataMig-cmode::*> lun import create -vserver datamig -path /vol/linuxvol/ext3lun -foreign-disk 830175420013
DataMig-cmode::*> lun import create -vserver datamig -path /vol/esxvol/linuxrdmvlun -foreign-disk 830175420018
DataMig-cmode::*> lun import create -vserver datamig -path /vol/esxvol/solrdmplun -foreign-disk 830175420019
----
. Überprüfen Sie die Erstellung des Importauftrags.
+
[listing]
----
DataMig-cmode::*> lun import show -vserver datamig
vserver foreign-disk   path                operation admin operational percent
                                         in progress state state       complete
-------------------------------------------------------------------------------
datamig 83017542000E   /vol/winvol/fdrive  import    stopped
                                                           stopped            0
datamig 83017542000F   /vol/winvol/gdrive  import    stopped
                                                           stopped            0
datamig 830175420010   /vol/linuxvol/bootlun
                                           import    stopped
                                                           stopped            0
3 entries were displayed.
----

