---
permalink: configure/fc-configure-adapter-initiator-mode.html 
sidebar: sidebar 
keywords:  
summary:  
---
= FC-Adapter für den Initiatormodus für ONTAP Foreign LUN Import (FLI)-Migration konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP FLI über FC erfordert einen FC-Adapter im Initiator-Modus auf der ONTAP Seite. Falls keine freien Initiator-Ports vorhanden sind, müssen Sie möglicherweise einen FC-Zieladapter-Port in den Initiator-Modus versetzen. Und wenn der FC-Adapter aktive FC-LIFs hat, müssen die aktiven FC-LIFs auf andere Adapter-Ports innerhalb desselben Fabrics verschoben werden.

.Schritte
. Die verfügbaren FC-Adapter anzeigen:
+
[source, cli]
----
fcp adapter show -status-oper online
----
+
*Beispielausgabe*

+
[listing]
----
  (network fcp adapter show)
                      Connection  Port    Admin    Operational
Node         Adapter  Established Address Status   Status          Topology
------------ -------- ----------- ------- -------- --------------- --------
ssan-a50-06a 3a       true        640a00  up       online          fabric
ssan-a50-06b 3b       true        640a00  up       online          fabric
ssan-a50-07a 3a       true        640e00  up       online          fabric
ssan-a50-07b 3b       true        640d00  up       online          fabric
----
. Nehmen Sie den Ziel-FC-Adapterport offline:
+
[source, cli]
----
fcp adapter modify -node <node_name> -adapter <adapter>> -status-admin down;
----
+
*Beispielausgabe*

+
[listing]
----
fcp adapter modify -node ssan-a50-06a -adapter 3a -status-admin down;
----
. Überprüfen Sie, ob der Status des Adapters „Down“ ist:
+
[source, cli]
----
fcp adapter show -node <node_name> -adapter <adapter>> -fields status-admin
----
+
*Beispielausgabe*

+
[listing]
----
ssan-a50-06-07::*> fcp adapter show -node ssan-a50-06a -adapter 3a -fields status-admin

node         adapter status-admin
------------ ------- ------------
ssan-a50-06a 3a      down
----
. Den FC-Adapteranschluss vom Zielmodus in den Initiatormodus umwandeln:
+
[source, cli]
----
system node hardware unified-connect modify -node <node_name> -adapter <adapter> -type initiator
----
+
*Beispiel*

+
[listing]
----
ssan-a50-06-07::*> system node hardware unified-connect modify -node ssan-a50-06a -adapter 3a -type initiator

Any changes will take effect after rebooting the system. Use the "system node reboot" command to reboot.
----
. Bringen Sie den Adapter wieder online:
+
[source, cli]
----
fcp adapter modify -node <node_name> -adapter <adapter> -status-admin up;
----
+
*Beispiel*

+
[listing]
----
ssan-a50-06-07::*> fcp adapter modify -node ssan-a50-06a -adapter 3a -status-admin up;
----
. Vergewissern Sie sich, dass der Adapter wieder online und im Initiatormodus ist:
+
[source, cli]
----
system node hardware unified-connect show
----
+
*Beispiel*

+
[listing]
----
ssan-a50-06-07::*> system node hardware unified-connect show
                       Current  Current    Pending  Pending    Admin
Node          Adapter  Mode     Type       Mode     Type       Status
------------  -------  -------  ---------  -------  ---------  -----------
ssan-a50-06a  3a       fc       target     -        initiator  offline << pending node reboot
ssan-a50-06b  3b       fc       target     -        -          online
ssan-a50-07a  3c       fc       target     -        -          online
ssan-a50-07a  3d       fc       initiator  -        -          online <<< already converted
ssan-a50-06-07::*>
----

